### ISSUE TITLE
Add historian

### ISSUE THREAD

**Issue by evandixon** [devnetmsu/devnet-website#9]

**Comment by brittf** [comment]
Here's the description:

Britt Faulkner is a Junior Software Engineering major. As the Historian of DevNet, he takes minutes and attendance at meetings. ["He also writes brief meeting reviews for the website." - (Add this if we get that feature set up later)]

**Comment by brittf** [comment]
![img_0995](https://user-images.githubusercontent.com/32182220/30788370-f3228330-a160-11e7-824b-9b163027684d.JPG)

This is the best picture I have. If you need a better one, I will have someone help me with that tomorrow.
